#!/usr/bin/env bash
# installing nginx and make it listening on port 80 

sudo apt-get update -y 
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
