#!/usr/bin/env bash
# installing nginx and make it listening on port 80 

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
nginx -s reload

