#!/usr/bin/env bash
# installing nginx and make it listening on port 80 

sudo apt-get update -y 
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
