#!/usr/bin/env bash
# making /redirect_me  redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.nginx-debian.html
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
