#!/usr/bin/env bash
# in this script we will configure nginx web server to serve a custome error message 

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
echo "Hello World!" > index.nginx-debian.html
sudo mv index.nginx-debian.html /var/www/html/
echo "Ceci n'est pas une page" > custom_404.html
sudo mv custom_404.html /var/www/html/
echo "server{
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
}" > default
sudo rm /etc/nginx/sites-available/default
sudo mv default /etc/nginx/sites-available/default
sudo service nginx restart
